#!/bin/bash

# This script should be saved in a git repo as a hook file, e.g. .git/hooks/pre-receive.
# It looks for scripts in the .git/hooks/pre-receive.d directory and executes them in order,
# passing along stdin. If any script exits with a non-zero status, this script exits.

script_dir=$(dirname $0)
hook_name=$(basename $0)

hook_dir="$script_dir/$hook_name.d"

if [[ -d $hook_dir ]]; then
  if [ ! -t 0 ] ; then
    stdin=$(cat)
  fi

  for hook in $hook_dir/*; do
    echo ">>> Running hook: $hook_name/$hook"
    echo
    echo "$stdin" | $hook "$@"

    exit_code=$?

    if [ $exit_code != 0 ]; then
      failed=1
    else
      echo "OK"
    fi

    echo ""
  done
fi

if [ "$failed" == 1 ] ; then
  exit 1
fi

exit 0
